name: DevSecOps - Release on push

on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x'

env:
  node-js-version: 20.x
  author-name: Marc Scheib
  author-email: marc.scheib@tech11.com

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release

    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js [${{ env.node-js-version }}]
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-js-version }}

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx --yes -p @semantic-release/changelog -p @semantic-release/git semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.author-name }}
          GIT_AUTHOR_EMAIL: ${{ env.author-email }}
